### ISSUE TITLE
Usar .env para informacoes sensiveis

### ISSUE THREAD

**Issue by CarlosZiegler** [marcoshenrique-dev/template-mongoDB-yarn#1]
Ola Marcos,

parabens pela sua iniciativa, como comentei anterioromente em um dos seus posts, eu criei um repositorio como template tambem, acho valido ao inves de usar um arquivo de configuracao (config.js) usar um arquivo de variaveis de ambiente (.env) tendo em vista que a url do mongo contem dados sensiveis, nao seria legal deixar ela exposta. Para isso da uma olhada nessa dependencia -> dotenv

**Comment by marcoshenrique-dev** [comment]
Massa! Obrigado pela indicação :) Vou dar uma olhada logo logo
